<?xml version="1.0"?>
<analyzerinfo checksum="442357544">
        <error id="arrayIndexOutOfBounds" severity="error" msg="Array &apos;id_sequenz[3]&apos; accessed at index 4, which is out of bounds." verbose="Array &apos;id_sequenz[3]&apos; accessed at index 4, which is out of bounds." cwe="788" hash="6332437718526642545">
            <location file0="C:\Users\Marcel\Desktop\Bachelorarbeit\SyntheticTestCases\CWE787\example1.cpp" file="C:\Users\Marcel\Desktop\Bachelorarbeit\SyntheticTestCases\CWE787\example1.cpp" line="13" column="27" info="Array index out of bounds"/>
        </error>
  <FileInfo check="ctu">
<function-call call-id="C:/Users/Marcel/Desktop/Bachelorarbeit/SyntheticTestCases/CWE787/example1.cpp:5:6" call-funcname="arraycopy" call-argnr="1" file="C:/Users/Marcel/Desktop/Bachelorarbeit/SyntheticTestCases/CWE787/example1.cpp" line="20" col="14" call-argexpr="dataArray" call-argvaluetype="7" call-argvalue="24"/>  </FileInfo>
  <FileInfo check="CheckUnusedFunctions">
    <functiondecl functionName="arraycopy" lineNumber="5"/>
    <functiondecl functionName="main" lineNumber="17"/>
    <functioncall functionName="arraycopy"/>
    <functioncall functionName="dataArray"/>
    <functioncall functionName="for"/>
    <functioncall functionName="i"/>
    <functioncall functionName="size"/>
    <functioncall functionName="sizeof"/>
  </FileInfo>
</analyzerinfo>
